{{- $identities := list }}

{{- range .Values.sourceS3Secrets }}
  {{- $src := lookup "v1" "Secret" $.Release.Namespace .name }}
  {{- if not $src }}
    {{- fail (printf "Secret %s not found" .name) }}
  {{- end }}

  {{- /* Resolve accessKey (accessKey OR S3_ACCESS_KEY) */}}
  {{- $rawAccessKey := or
        (index $src.data "accessKey")
        (index $src.data "S3_ACCESS_KEY")
  }}
  {{- $accessKey := required
        (printf "Secret %s is missing accessKey or S3_ACCESS_KEY" .name)
        $rawAccessKey
        | b64dec
  }}

  {{- /* Resolve secretKey (secretKey OR S3_SECRET_KEY OR S3_SECRET_ACCESS) */}}
  {{- $rawSecretKey := or
        (index $src.data "secretKey")
        (index $src.data "S3_SECRET_KEY")
        (index $src.data "S3_SECRET_ACCESS")
  }}
  {{- $secretKey := required
        (printf "Secret %s is missing secretKey or S3_SECRET_KEY" .name)
        $rawSecretKey
        | b64dec
  }}

  {{- $identities = append $identities (dict
        "name" .name
        "accessKey" $accessKey
        "secretKey" $secretKey
        "actions" .actions
    ) }}
{{- end }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.s3_secret }}
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
stringData:
  seaweedfs_s3_config: |
    {
      "identities": [
        {{- range $i, $id := $identities }}
        {{- if $i }},{{ end }}
        {
          "name": "{{ $id.name }}",
          "credentials": [
            {
              "accessKey": "{{ $id.accessKey }}",
              "secretKey": "{{ $id.secretKey }}"
            }
          ],
          "actions": {{ toJson $id.actions }}
        }
        {{- end }}
      ]
    }
