apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.s3_secret }}
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
stringData:
  seaweedfs_s3_config: |
    {
      "identities": [
        {{- range $index, $id := .Values.s3Identities }}
                {{- if $index }},{{ end }}
                {
                  "name": "{{ $id.name }}",
                  "credentials": [
                    {
                      "accessKey": "{{ $id.accessKey }}",
                      "secretKey": "{{ $id.secretKey }}"
                    }
                  ],
                  "actions": {{ toJson $id.actions }}
                }
        {{- end }}
      ]
    }
