{{- $root := . }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-writer
  labels:
    {{- include "ocp-oauth-htpasswd.labels" $root | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer
  labels:
    {{- include "ocp-oauth-htpasswd.labels" $root | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-writer
  labels:
    {{- include "ocp-oauth-htpasswd.labels" $root | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: secret-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-writer
