apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-writer

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "apply", "get", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-writer
subjects:
  - kind: ServiceAccount
    name: secret-writer
roleRef:
  kind: Role
  name: secret-writer
  apiGroup: rbac.authorization.k8s.io
