apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: airflow
  namespace: kubocd-system
spec:
  description: "Apache Airflow for workflow orchestration with Spark integration"
  package:
    repository: quay.io/okdp/sandbox-packages-v0.1/airflow
    tag: 1.17.0-p01
  parameters:
    postgresqlEnabled: true
    redisEnabled: true
    executorType: "CeleryExecutor"
    webserverReplicas: 1
    schedulerReplicas: 1
    workerReplicas: 1
    ingressEnabled: true
    ingressHost: "airflow.okdp.local"
    dagsPersistenceEnabled: false
    logsPersistenceEnabled: false
  targetNamespace: airflow
  createNamespace: true
