apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: airflow
  namespace: default
spec:
  description: "Apache Airflow for workflow orchestration with Spark integration"
  package:
    repository: quay.io/okdp/sandbox-packages-v0.1/airflow
    tag: 2.9.3-p02
  targetNamespace: default
  createNamespace: false
