apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: airflow
  namespace: kubocd-system
spec:
  description: "Apache Airflow for workflow orchestration with Spark integration"
  package:
    repository: quay.io/okdp/sandbox-packages-v0.1/airflow
    tag: 2.9.3-p01
  targetNamespace: airflow
  createNamespace: true
