apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: cert-manager
  namespace: kubocd-system
spec:
  description: "Certificate management for Kubernetes with trust-manager and issuers"
  package:
    repository: quay.io/okdp/sandbox-packages-v0.1/cert-manager
    tag: 1.17.1-p06
    interval: 30m
    timeout: 10m
  parameters:
    trust:
      enabled: true
      bundle:
        name: certs-bundle
        target:
          configMap:
            enabled: true
            key: "root-certs.pem"
          secret:
            enabled: true
    issuers:
      enabled: true
      selfSignedClusterIssuers:
        - name: default-issuer
          certificate:
            commonName: "OKDP Sandbox Self-Signed CA"
            organization: "OKDP"
            country: "FR"
            validity: "8760h"
            algorithm: "ECDSA"
            size: 256
  contexts:
    - name: default
      namespace: kubocd-system
  targetNamespace: cert-manager
  createNamespace: true 