apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: local-secrets-provider
  namespace: kubocd-system
spec:
  createNamespace: true
  description: |
    A centralized Helm chart for managing and distributing local testing shared configurations,
    secrets, services, and environment variables across multiple platform components.
  package:
    interval: 30m
    repository: quay.io/okdp/sandbox-packages-v0.1/local-secrets-provider
    tag: 1.0.0-p02
    timeout: 10m
  targetNamespace: default