#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# you may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: tools
  namespace: kubocd-system
spec:
  description: "Miscellaneous Kubernetes tools for cluster management"
  package:
    repository: quay.io/okdp/sandbox-packages-v0.1/tools
    tag: 1.0.0-p01
    interval: 30m
    timeout: 10m
  parameters:
    namespace: kube-tools
    reloader:
      enabled: true
    replicator:
      enabled: true
    secretGenerator:
      enabled: true
  targetNamespace: kube-tools
  createNamespace: true 