{{- range .Values.caClusterIssuers }}
{{- include "cert-issuers.validateCAIssuer" . }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
  labels:
    {{- include "cert-issuers.labels" $ | nindent 4 }}
    cert-issuers.okdp.io/type: "ca"
    cert-issuers.okdp.io/issuer-name: {{ .name | quote }}
  annotations:
    cert-issuers.okdp.io/managed-by: "cert-issuers-chart"
    cert-issuers.okdp.io/version: {{ $.Chart.Version | quote }}
spec:
  ca:
    secretName: {{ .name }}

{{- if .ca_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "cert-issuers.certificateNamespace" $ }}
  labels:
    {{- include "cert-issuers.labels" $ | nindent 4 }}
    cert-issuers.okdp.io/type: "ca-secret"
    cert-issuers.okdp.io/issuer-name: {{ .name | quote }}
  annotations:
    cert-issuers.okdp.io/managed-by: "cert-issuers-chart"
    cert-issuers.okdp.io/version: {{ $.Chart.Version | quote }}
    {{- if $.Values.replication.enabled }}
    {{- include "cert-issuers.replicationAnnotations" (list $ .name) | nindent 4 }}
    {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .ca_crt }}
  tls.key: {{ .ca_key }}
{{- end }}

{{- if .ca_crt }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-ca
  namespace: {{ include "cert-issuers.certificateNamespace" $ }}
  labels:
    {{- include "cert-issuers.labels" $ | nindent 4 }}
    cert-issuers.okdp.io/type: "ca-public"
    cert-issuers.okdp.io/issuer-name: {{ .name | quote }}
  annotations:
    cert-issuers.okdp.io/managed-by: "cert-issuers-chart"
    cert-issuers.okdp.io/version: {{ $.Chart.Version | quote }}
    {{- if $.Values.replication.enabled }}
    {{- include "cert-issuers.replicationAnnotations" (list $ .name) | nindent 4 }}
    {{- end }}
type: Opaque
data:
  ca.crt: {{ .ca_crt }}
{{- end }}

{{- end }} 