# Default values for cert-issuers
# This chart creates cert-manager ClusterIssuers and trust bundles

# Global settings
global:
  # Namespace where certificates will be stored
  certificateNamespace: ""

# CA-based ClusterIssuers configuration
caClusterIssuers: []
# Each item should contain:
# - name: issuer-name                    # Name of the ClusterIssuer
#   ca_crt: LS0tLS1CRUdJTi...           # Base64 encoded CA certificate (required)
#   ca_key: LS0tLS1CRUdJTi...           # Base64 encoded CA private key (optional)
#
# Examples:
# - name: my-ca-issuer
#   ca_crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
#   ca_key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...
#
# WARNING: Including private keys in values is a security risk
# Consider using external secret management for ca_key values

# Self-signed ClusterIssuers configuration  
selfSignedClusterIssuers: []
# Each item should contain:
# - name: issuer-name                    # Name of the ClusterIssuer
#   certificate:                         # Certificate configuration (optional)
#     commonName: "My CA"                # Common name for the certificate
#     organization: "My Org"             # Organization name
#     country: "US"                      # Country code
#     validity: "8760h"                  # Certificate validity period (default: 1 year)
#     algorithm: "ECDSA"                 # Private key algorithm (RSA, ECDSA)
#     size: 256                          # Key size
#
# Examples:
# - name: self-signed-ca
#   certificate:
#     commonName: "Self-Signed CA"
#     organization: "OKDP"
#     country: "FR"

# Trust bundle configuration (requires trust-manager)
bundle:
  # Enable bundle creation
  enabled: false
  
  # Bundle name - will be used for target ConfigMap/Secret name
  name: "certs-bundle"
  
  # Include default system CAs
  useDefaultCAs: true
  
  # Target configuration
  target:
    # Create a ConfigMap with the bundle
    configMap:
      enabled: false
      key: "root-certs.pem"
    
    # Create a Secret with the bundle  
    secret:
      enabled: false
      key: "ca.crt"
    
    # Additional formats
    additionalFormats:
      jks:
        enabled: false
        key: "bundle.jks"
      pkcs12:
        enabled: false
        key: "bundle.p12"
  
  # Namespace selector for bundle distribution
  namespaceSelector:
    matchLabels: {}  # Empty means all namespaces

# Certificate replication settings
replication:
  # Enable certificate replication across namespaces
  enabled: true
  
  # Replication method: "kubed" or "replicator"
  method: "replicator"
  
  # Namespace pattern for replication (regex)
  allowedNamespaces: ".*"

# Security settings
security:
  # Enable Pod Security Standards
  podSecurityStandards:
    enabled: false
    enforce: "restricted" 