#
# Copyright 2026 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# you may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

apiVersion: kubocd.kubotal.io/v1alpha1
kind: Context
metadata:
  name: default
  namespace: kubocd-system
spec:
  context:
    proxy:
      httpProxy: ~
      httpsProxy: ~
      noProxy: ~
    ingress:
      suffix: okdp.sandbox
      className: nginx

    certificateIssuers:
      selfSigned:
        name: default-issuer
        
    storageClass:
      data: standard
      workspace: standard

    okdp:
      packageRepository: quay.io/okdp/sandbox-packages-v0.1
      clusters:
        - id: sandbox
          name: "OKDP Sandbox Cluster"
          env: dev
          auth:
            inCluster: true
      catalogs:
        - id: Dataviz
          name: "Dataviz catalog"
          description: "Dataviz packages"
          packages:
            - name: superset
        - id: Notebook
          name: "Notebooks catalog"
          description: "Notebooking packages"
          packages:
            - name: jupyterhub
        - id: Spark
          name: "Spark packages"
          description: "Spark packages"
          packages:
            - name: spark-history-server
        - id: Storage
          name: "Storage catalog"
          description: "Storage packages"
          packages:
            - name: seaweedfs
        - id: Interactive-Query
          name: "Interactive Query"
          description: "Interactive-query packages"
          packages:
            - name: trinodb
        - id: Data-Catalog
          name: "Data Catalog"
          description: "Central metadata catalog packages"
          packages:
            - name: hive-metastore
        - id: Applications
          name: "OKDP Examples"
          description: "A collection of hands-on okdp examples"
          packages:
            - name: okdp-examples
      services:
        - Notebook
        - Spark
        - Dataviz
        - Interactive-Query
        - Data-Catalog
        - Storage
        - Applications
      kadCatalogsInfo:
        Interactive-Query:
          displayName: "Interactive Query"
          menuIcon: "fa-solid fa-database"
        Data-Catalog:
          displayName: "Data Catalog"
          menuIcon: "fa-solid fa-sitemap"
        Applications:
          displayName: "Applications"
          menuIcon: "fa-solid fa-code"
      kadServicesInfo:
        hive-metastore:
          icon: "okdp-notext.svg"
          menuIcon: "fa-solid fa-book"
          description: |
            The central repository of metadata for Hive tables and partitions, providing clients including Hive, Impala, and Spark access through the metastore service API. 
            A fundamental building block for modern data lakes.
          home: "https://hive.apache.org"
        okdp-examples:
          icon: "okdp-notext.svg"
          menuIcon: "fa-solid fa-code"
          description: |
            A collection of hands-on examples, helper utilities, Jupyter notebooks, and data workflows 
            that showcases how to work with the OKDP Platform.
          home: "https://github.com/okdp/okdp-examples"
        seaweedfs:
          description: |
            SeaweedFS is a simple and highly scalable distributed file system. There are the objectives to store billions of files and to serve the files fast!
          home: "https://seaweedfs.com/"

    hiveMetastore:
      database:
        type: postgresql
        driver: org.postgresql.Driver
        host: postgresql-instance-rw.cnpg-system.svc.cluster.local
        port: 5432
        name: hms
        credentialsSecret:
          name: creds-hms-db
          usernameKey: username
          passwordKey: password
      storage:
        provider: s3
        s3:
          apiUrl: https://seaweedfs-seaweedfs-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}
          bucket: hive
          bucketAnonymousRead: true
          warehouseDir: hive-warehouse/
          credentialsSecret:
            name: creds-hms-s3
            accessKeyKey: accessKey
            secretKeyKey: secretKey
          actions:
            - Admin
        tls:
          enabled: true
          insecureSkipVerify: true
      endpoint:
        url: thrift://hive-metastore.{{ .Release.namespace }}.svc.cluster.local:9083

    trino:
      metastore:
        uri: thrift://hive-metastore.{{ .Release.namespace }}.svc.cluster.local:9083
      auth:
        enabled: true
        method: oidc
        basic:
          username: trino
          #credentialsSecret:
          #  name: creds-trino
          # ....
        oidc:
          provider: keycloak
          issuerUri: "https://keycloak.{{ .Context.ingress.suffix }}/realms/master"
          scope: "openid profile email groups"
          usePKCE: true
          insecureSkipVerify: true
          credentialsSecret:
            name: creds-oidc
            clientIdKey: client_id
            clientSecretKey: client_secret
      storage:
        provider: s3
        s3:
          apiUrl: https://seaweedfs-seaweedfs-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}
          credentialsSecret:
            name: creds-trino-s3
            accessKeyKey: S3_ACCESS_KEY
            secretKeyKey: S3_SECRET_ACCESS
          actions:
            - Admin
          tls:
            enabled: true
            insecureSkipVerify: true
      endpoint:
        url: https://trino-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}

    superset:
      database:
        name: superset
        host: postgresql-instance-rw.cnpg-system.svc.cluster.local
        port: 5432
        credentialsSecret:
          name: creds-superset-db
          usernameKey: username
          passwordKey: password
      # Secret Key for Superset's Flask App
      secret:
        name: creds-superset-secret-key
        key: superset_secret_key
      load_examples:
        jdbc_uri: "postgresql+psycopg2://$DB_EXAMPLES_USER:$DB_EXAMPLES_PASS@$DB_EXAMPLES_HOST:$DB_EXAMPLES_PORT/$DB_EXAMPLES_NAME?options=-csearch_path%3Dmain"
        database:
          name: superset-examples
          host: postgresql-instance-rw.cnpg-system.svc.cluster.local
          port: 5432
          credentialsSecret:
            name: creds-superset-examples-db
            usernameKey: username
            passwordKey: password
      redis:
        host: ~
        port: 6379
        credentialsSecret:
          name: creds-redis
          usernameKey: username
          passwordKey: password
      auth:
        enabled: true
        method: oidc
        oidc:
          provider: keycloak
          baseUrl: "https://keycloak.{{ .Context.ingress.suffix }}:443/realms/master/protocol/openid-connect"
          scope: "openid profile email groups"
          usePKCE: true
          insecureSkipVerify: true
          credentialsSecret:
            name: creds-oidc
            clientIdKey: client_id
            clientSecretKey: client_secret
      dataSources: |
        databases:
        - database_name: trino
          sqlalchemy_uri: "trino://trino@trino-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}:443/lakehouse/nyc_tripdata?http_scheme=https&verify=false"
          extra: |
            {
              "engine_params": {},
              "metadata_params": {},
              "connect_args": {
                "http_scheme": "https",
                "verify": false
              },
              "metadata_cache_timeout": {},
              "schemas_allowed_for_file_upload": []
            }
          allow_run_async: true
          allow_dml: true
          allow_ctas: true
          allow_cvas: true
          expose_in_sqllab: true
      endpoint:
        url: https://superset-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}

    jupyter:
      storage:
        provider: s3
        s3:
          apiUrl: https://seaweedfs-seaweedfs-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}
          credentialsSecret:
            name: creds-jupyter-s3
            accessKeyKey: S3_ACCESS_KEY
            secretKeyKey: S3_SECRET_KEY
          actions:
            - Admin
          tls:
            enabled: true
            insecureSkipVerify: true
      auth:
        enabled: true
        method: oidc
        oidc:
          provider: keycloak
          baseUrl: "https://keycloak.{{ .Context.ingress.suffix }}/realms/master/protocol/openid-connect"
          credentialsSecret:
            name: creds-oidc
            clientIdKey: client_id
            clientSecretKey: client_secret
      endpoint:
        url: https://jupyter-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}

    sparkRBAC:
      rbac:
        create: true
      serviceAccount:
        create: true
        name: "spark"
        automountServiceAccountToken: true

    sparkHistory:
      eventsLogDir: s3a://spark-events/event-logs/
      storage:
        provider: s3
        s3:
          apiUrl: https://seaweedfs-seaweedfs-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}
          bucket: spark-events
          bucketAnonymousRead: true
          credentialsSecret:
            name: creds-spark-history-s3
            accessKeyKey: accessKey
            secretKeyKey: secretKey
          actions:
            - Admin
          tls:
            enabled: true
            insecureSkipVerify: true
      auth:
        enabled: true
        method: oidc
        oidc:
          provider: keycloak
          issuerUri: "https://keycloak.{{ .Context.ingress.suffix }}/realms/master"
          scope: "openid+profile+email+offline_access+groups"
          usePKCE: true
          insecureSkipVerify: true
          credentialsSecret:
            name: creds-oidc
            clientIdKey: client_id
            clientSecretKey: client_secret
      endpoint:
        url: https://spark-history-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}

    examples:
      storage:
        provider: s3
        s3:
          apiUrl: https://seaweedfs-seaweedfs-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}
          credentialsSecret:
            name: creds-examples-s3
            accessKeyKey: S3_ACCESS_KEY
            secretKeyKey: S3_SECRET_KEY
          actions:
            - Admin
          tls:
            enabled: true
            insecureSkipVerify: true
      trino:
        url: https://trino-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}

    #### OKDP External Dependencies #################################
    ###### Pre-provision the environment for the Sandbox ############
    #################################################################
    # Create all the kubernetes secrets required by the services
    # The provisioning is local, but you can provide them using external secrets or vault provider
    # In order to have a predictable behaviour on re-deployment, we provision the secrets statically
    localSecretsProvider:
      info: |
        Currently, the secrets are created inside the package `local-secrets-provider.yaml` itself.
        We add an ability for KuboCD to reuse/inherit (substitution) the context variables later so that we can list them here.

    keycloak:
      database:
        name: keycloak
        host: postgresql-instance-rw.cnpg-system.svc.cluster.local
        port: 5432
        credentialsSecret:
          name: creds-keycloak-db
          usernameKey: username
          passwordKey: password
      realm:
        name: master
        displayName: "OKDP internal Realm"
        accessTokenLifespan: 3600
      users:
        - username: usera
          email: usera@okdp.io
          firstName: usera
          lastName: usera
          password: usera
          roles: [teama]
        - username: userb
          email: userb@okdp.io
          firstName: userb
          lastName: userb
          password: userb
          roles: [teamb]
        - username: adm
          email: adm@okdp.io
          firstName: adm
          lastName: adm
          password: adm
          roles: [admins]
      groups:
        - name: teama
        - name: teamb
        - name: admins
      roles:
        - name: teama
        - name: teamb
        - name: admins
      clients:
        - clientId: public-oidc-client
          name: public-oidc-client
          publicClient: true
          redirectUris:
            - "https://okdp-server.{{ .Context.ingress.suffix }}/swagger/oauth2-redirect.html"
            - "https://okdp-ui.{{ .Context.ingress.suffix }}/index.html"
            - "https://okdp-ui.{{ .Context.ingress.suffix }}/silent-refresh.html"
          webOrigins:
            - "https://okdp-server.{{ .Context.ingress.suffix }}"
            - "https://okdp-ui.{{ .Context.ingress.suffix }}"
        - clientId: confidential-oidc-client
          name: confidential-oidc-client
          secret: secret1
          publicClient: false
          redirectUris:
            - "https://*"
          webOrigins:
            - "https://*"
          defaultClientScopes:
            - web-origins
            - acr
            - roles
            - profile
            - groups
            - basic
            - email
          optionalClientScopes:
            - address
            - phone
            - organization
            - offline_access
            - microprofile-jwt
      clientScopes:
        - name: groups
          description: "Groups scope"
          protocol: openid-connect
          attributes:
            include.in.token.scope: "false"
            display.on.consent.screen: "true"
          protocolMappers:
            - name: roles_map_to_groups
              protocol: openid-connect
              protocolMapper: oidc-usermodel-realm-role-mapper
              config:
                access.token.claim: "true"
                claim.name: groups
                id.token.claim: "true"
                introspection.token.claim: "true"
                jsonType.label: String
                lightweight.claim: "true"
                multivalued: "true"
                userinfo.token.claim: "true"

    # Provision the following databases and expose the final endpoint
    databaseServer:
      provider: postgresql
      postgresql:
        databases:
          - name: hms
            owner:
              username: "hms"
              passwordSecret: creds-hms-db
          - name: superset
            owner:
              username: "superset"
              passwordSecret: creds-superset-db
          - name: keycloak
            owner:
              username: "keycloak"
              passwordSecret: creds-keycloak-db
          - name: seaweedfs-default
            owner:
              username: "seaweedfs"
              passwordSecret: creds-seaweedfs-db
          - name: superset-examples
            owner:
              username: "examples"
              passwordSecret: creds-superset-examples-db
            schemas:
              - main
      endpoint:
        host: postgresql-instance-rw.cnpg-system.svc.cluster.local
        port: 5432

    seaweedfs:
      endpoint:
        filerUrl: https://seaweedfs-seaweedfs-console-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}
        s3Url: https://seaweedfs-seaweedfs-{{ .Release.namespace }}.{{ .Context.ingress.suffix }}
      database:
        name: seaweedfs
        host: postgresql-instance-rw.cnpg-system.svc.cluster.local
        port: 5432
        credentialsSecret:
          name: creds-seaweedfs-db
          usernameKey: username
          passwordKey: password
      s3:
        s3_secret: creds-seaweedfs-secret
        credentialsSecret:
            name: creds-seaweedfs-s3
            accessKeyKey: accessKey
            secretKeyKey: secretKey
        actions:
            - Admin
      info: |
        We add an ability for KuboCD to reuse/inherit (variable substitution) later.
        All the required access keys for the services are provisioned in the package seaweedfs.yaml itself.
